language: java
jdk:
- oraclejdk8
os:
- linux

sudo: false
  addons:
    packages:
      - oracle-java8-installer
notifications:
  slack:
    secure: g+6lVaG8OFc5R6pd4l9+SEcrklm1a+RBtyl3OcsLNNU3oh9XHKWHLReJdbK0rXo3UgUlucj+g8hs/jeGDFIg9I+jAEKrnT6YkaIHrd8CefZcXq9A5koTqXxc0uZaQulu4S2ajoKF7/KxS8Z9E6VUIuY1uos9WfQQtmM8ADxNIBS/Vq6j8IVgKd9Vri668C1BLvTSuWDBNbRSZZj8RNNANjjECiAimkGQpyj0cP0ulvpr8m9toVU9q5tPFHt/9bXbxW0jaDRTM0ulP8XZzDxF5t71IxIlVZObfQd46BUlddZQYjZLN/9slyMKOCbUjSK2DWZY00iOqVLZldtwlUxtlE5fsYKrByO5U/aODNYs1w/1N578HaF6PrfEpJHjkzPU8GAiTemQroqLofR+utDKZ9KbzG6RQpbyGRwY3MvZaDqbUPGF8A/PqwEGje6UIdUzX7aTwhy+Swgr8vwBkZSRMe70URa34myUqxtQn8qPz2pbUCqiVV67xkcxaStnIzLpSiUZRjyHzV+RSQv+rdIA/ezdyGjdVwjTV6CLAHAIWSfS7uFsL/N/fWJWhcHmiPjNm8xPeHAHkFzStdvGX0NRMLBw0IojMnn5faOZ/7scIIcKsigQDtzycx4dr9k6ZOuSBWSUtY1ebJ/iH/tu/0Thc0zYj/w9Gh/zov2muEXpiRI=
