INSERT INTO Services VALUES (NULL, 'Addiction Recovery Program');
INSERT INTO Services VALUES (NULL, 'Admitting/Registration');
INSERT INTO Services VALUES (NULL, 'Allergy ');
INSERT INTO Services VALUES (NULL, 'Arthritis Center');
INSERT INTO Services VALUES (NULL, 'ATM ');
INSERT INTO Services VALUES (NULL, 'Atrium Café');
INSERT INTO Services VALUES (NULL, 'Audiology');
INSERT INTO Services VALUES (NULL, 'Boston ENT Associates');
INSERT INTO Services VALUES (NULL, 'Breast Center');
INSERT INTO Services VALUES (NULL, 'Brigham and Womens Primary Physicians');
INSERT INTO Services VALUES (NULL, 'Brigham Dermatology Associates');
INSERT INTO Services VALUES (NULL, 'Cafeteria');
INSERT INTO Services VALUES (NULL, 'Cardiac Rehabilitation');
INSERT INTO Services VALUES (NULL, 'Cardiology');
INSERT INTO Services VALUES (NULL, 'Case Management');
INSERT INTO Services VALUES (NULL, 'Center for Metabolic Health and Bariatric Surgery');
INSERT INTO Services VALUES (NULL, 'Center for Preoperative Evaluation');
INSERT INTO Services VALUES (NULL, 'Center for Weight Management and Metabolic Surgery');
INSERT INTO Services VALUES (NULL, 'Chapel and Chaplaincy Services');
INSERT INTO Services VALUES (NULL, 'Colorectal Surgery');
INSERT INTO Services VALUES (NULL, 'Diabetes Program');
INSERT INTO Services VALUES (NULL, 'Dialysis Clinic');
INSERT INTO Services VALUES (NULL, 'Doherty Conference Room');
INSERT INTO Services VALUES (NULL, 'Emergency Department');
INSERT INTO Services VALUES (NULL, 'Endocrinology  ');
INSERT INTO Services VALUES (NULL, 'Eye Care Specialists ');
INSERT INTO Services VALUES (NULL, 'Family Care Associates');
INSERT INTO Services VALUES (NULL, 'Foot and Ankle Center  ');
INSERT INTO Services VALUES (NULL, 'Gastroenterology  ');
INSERT INTO Services VALUES (NULL, 'Gastroenterology Associates ');
INSERT INTO Services VALUES (NULL, 'General Surgery  ');
INSERT INTO Services VALUES (NULL, 'Geriatrics/Senior Health');
INSERT INTO Services VALUES (NULL, 'GI Endoscopy');
INSERT INTO Services VALUES (NULL, 'Gift Shop');
INSERT INTO Services VALUES (NULL, 'Hand and Upper Extremity Center');
INSERT INTO Services VALUES (NULL, 'Headache Center');
INSERT INTO Services VALUES (NULL, 'Hematology');
INSERT INTO Services VALUES (NULL, 'Human Resources');
INSERT INTO Services VALUES (NULL, 'Huvos Auditorium');
INSERT INTO Services VALUES (NULL, 'ICU');
INSERT INTO Services VALUES (NULL, 'Infectious Diseases ');
INSERT INTO Services VALUES (NULL, 'Information');
INSERT INTO Services VALUES (NULL, 'Inpatient Hemodialysis');
INSERT INTO Services VALUES (NULL, 'Interpreter Services');
INSERT INTO Services VALUES (NULL, 'John R. Graham Headache Center ');
INSERT INTO Services VALUES (NULL, 'Laboratory');
INSERT INTO Services VALUES (NULL, 'Mammography');
INSERT INTO Services VALUES (NULL, 'Mary Ann Tynan Conference Rooms');
INSERT INTO Services VALUES (NULL, 'Medical Library');
INSERT INTO Services VALUES (NULL, 'Medical Records ');
INSERT INTO Services VALUES (NULL, 'Medical Specialties');
INSERT INTO Services VALUES (NULL, 'Mens Health Center');
INSERT INTO Services VALUES (NULL, 'Mohs and Dermatologic Surgery ');
INSERT INTO Services VALUES (NULL, 'Neurology  ');
INSERT INTO Services VALUES (NULL, 'Neurology/Sleep Division');
INSERT INTO Services VALUES (NULL, 'Neurosurgery');
INSERT INTO Services VALUES (NULL, 'Nutrition - Weight Loss Surgery');
INSERT INTO Services VALUES (NULL, 'Nutrition Clinic');
INSERT INTO Services VALUES (NULL, 'Obstetrics and Gynecology Associates');
INSERT INTO Services VALUES (NULL, 'Orthopaedics Associates');
INSERT INTO Services VALUES (NULL, 'Orthopedics Center');
INSERT INTO Services VALUES (NULL, 'Otolaryngology');
INSERT INTO Services VALUES (NULL, 'Outpatient Infusion Center');
INSERT INTO Services VALUES (NULL, 'Pain Management Center');
INSERT INTO Services VALUES (NULL, 'Pariser Conference Room');
INSERT INTO Services VALUES (NULL, 'Patient Financial Services');
INSERT INTO Services VALUES (NULL, 'Patient Relations');
INSERT INTO Services VALUES (NULL, 'Physical Therapy');
INSERT INTO Services VALUES (NULL, 'Plastic Surgery');
INSERT INTO Services VALUES (NULL, 'Psychiatry');
INSERT INTO Services VALUES (NULL, 'Psychology - Weight Loss Surgery');
INSERT INTO Services VALUES (NULL, 'Pulmonary  ');
INSERT INTO Services VALUES (NULL, 'Radiology');
INSERT INTO Services VALUES (NULL, 'Rehabilitation Services');
INSERT INTO Services VALUES (NULL, 'Renal  ');
INSERT INTO Services VALUES (NULL, 'Rheumatology Center');
INSERT INTO Services VALUES (NULL, 'Roslindale Pediatric Associates ');
INSERT INTO Services VALUES (NULL, 'Sadowsky Conference Room');
INSERT INTO Services VALUES (NULL, 'Sagoff Breast Imaging and Diagnostic Center');
INSERT INTO Services VALUES (NULL, 'Saslow Conference Room');
INSERT INTO Services VALUES (NULL, 'Sleep Medicine and Endocrinology Center');
INSERT INTO Services VALUES (NULL, 'Sleep Testing Center                     ');
INSERT INTO Services VALUES (NULL, 'Social Work');
INSERT INTO Services VALUES (NULL, 'Special Testing');
INSERT INTO Services VALUES (NULL, 'Spine Center');
INSERT INTO Services VALUES (NULL, 'Suburban Eye Specialists ');
INSERT INTO Services VALUES (NULL, 'Surgical Specialties');
INSERT INTO Services VALUES (NULL, 'Taiclet Family Center');
INSERT INTO Services VALUES (NULL, 'Urology');
INSERT INTO Services VALUES (NULL, 'Valet Parking');
INSERT INTO Services VALUES (NULL, 'Vascular Surgery  ');
INSERT INTO Services VALUES (NULL, 'Volunteer Services');
INSERT INTO Services VALUES (NULL, 'Kiosk');
INSERT INTO Services VALUES (NULL, 'Shutte Pickup');
INSERT INTO Services VALUES (NULL, 'Hillside Lobby');